apiVersion: v1
kind: Pod
metadata:
  name: curl-test-pod
  namespace: music-game  # Replace with your namespace if necessary
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ['sleep', '3600']  # Keep the pod running
