apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-storage-pvc
  namespace: music-game-spotify
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
