apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: music-game
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: quay.io/rhn_support_kquinn/fe_revised_artist_sep_remove_song_select:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: cache-volume
          mountPath: /var/cache/nginx
        env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config  # Reference the existing ConfigMap
              key: BACKEND_URL
        securityContext:  # Add securityContext for running as root
          runAsUser: 0               # Run as root user (UID 0)
          allowPrivilegeEscalation: true  # Allow privilege escalation if needed
        command: ["/bin/sh"]
        args: ["-c", 
        "envsubst '${BACKEND_URL}' < /usr/share/nginx/html/index.html.template > /usr/share/nginx/html/index.html && \
         envsubst '${BACKEND_URL}' < /usr/share/nginx/html/script.js.template > /usr/share/nginx/html/script.js && \
         envsubst '${BACKEND_URL}' < /etc/nginx/nginx.conf.template > /tmp/nginx.conf && \
         mv /tmp/nginx.conf /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
      volumes:
      - name: cache-volume
        emptyDir: {}
