apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: music-game-spotify
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: quay.io/rhn_support_kquinn/fe-spotify-admin:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: cache-volume
          mountPath: /var/cache/nginx
        - name: html-volume
          mountPath: /tmp/html
        env:
        - name: BACKEND_SERVICE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: BACKEND_URL
        command: ["/bin/sh"]
        args: ["-c",
        "mkdir -p /tmp/html /tmp/logs && \
         cp -r /usr/share/nginx/html/* /tmp/html/ && \
         cp /usr/share/nginx/html/index.html.template /tmp/html/index.html && \
         cp /usr/share/nginx/html/script.js.template /tmp/html/script.js && \
         cp /usr/share/nginx/html/admin.html.template /tmp/html/admin.html && \
         cp /usr/share/nginx/html/admin-script.js.template /tmp/html/admin-script.js && \
         export BACKEND_URL=${BACKEND_SERVICE} && envsubst '${BACKEND_URL}' < /etc/nginx/nginx.conf.template | sed 's|/usr/share/nginx/html|/tmp/html|g' | sed 's|/var/log/nginx|/tmp/logs|g' > /tmp/nginx.conf && \
         nginx -c /tmp/nginx.conf -g 'daemon off;'"]
      volumes:
      - name: cache-volume
        emptyDir: {}
      - name: html-volume
        emptyDir: {}
