apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: music-game-spotify
  labels:
    app: nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: quay.io/rhn_support_kquinn/middleware-spotify:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: MONGO_URL
          value: 'mongodb://mongodb-service:27017'
        - name: DB_NAME
          value: musicgame
        - name: ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: ALLOWED_ORIGINS
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: BACKEND_URL
        # Spotify API credentials
        - name: SPOTIFY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: spotify-credentials
              key: SPOTIFY_CLIENT_ID
        - name: SPOTIFY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: spotify-credentials
              key: SPOTIFY_CLIENT_SECRET
        - name: SPOTIFY_REDIRECT_URI
          valueFrom:
            secretKeyRef:
              name: spotify-credentials
              key: SPOTIFY_REDIRECT_URI
        - name: AUDIO_UPLOAD_DIR
          value: '/usr/src/app/uploads/audio'
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-url-config
              key: FRONTEND_URL
        volumeMounts:
        - name: audio-storage
          mountPath: /usr/src/app/uploads
      volumes:
      - name: audio-storage
        persistentVolumeClaim:
          claimName: audio-storage-pvc
