apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: music-game
spec:
  type: ClusterIP  # Change from LoadBalancer to ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: nodejs-app
